### ISSUE TITLE
Windows Popen error

### ISSUE THREAD

**Issue by haje01** [jason-kane/PyYapf#28] opened 2016-11-18 04:23 UTC
In Windows, the plugin raises error: "OSError: [WinError 6] The handle is invalid"
To fix this, you need `stdin=subprocess.PIPE` as `Popen` parameter

```
diff --git a/PyYapf.py b/PyYapf.py
index 1e433b6..76619bc 100644
--- a/PyYapf.py
+++ b/PyYapf.py
@@ -245,6 +245,7 @@ class Yapf:
                         self.popen_args,
                         stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE,
+                        stdin=subprocess.PIPE,
                         cwd=self.popen_cwd,
                         env=self.popen_env,
                         startupinfo=self.popen_startupinfo)
```

**Comment by catch22** [comment] 2016-11-18 10:15
I can't reproduce this problem (running Windows). The current code follows the Python docs which seem to suggest that one only needs `stdin=PIPE` if one actually sends stuff to the program's `stdin`.

However, I'm happy to merge this if it indeed fixes your problem.

**Comment by jason-kane** [comment] 2018-02-06 17:28
The upstream bug was fixed a few months ago (oct 24, 2017 actually); we should be able to switch to use_stdin and get rid of all the tempfile cruft.  I'll take a look when I get a few cycles.

**Comment by jason-kane** [comment] 2018-07-04 15:46
(was merged)

**Closed by jason-kane** 2018-07-04 15:46 UTC
